/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.services.TrainService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train booking app");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        } catch (IOException x) {
            System.out.println("There is something wrong");
            return;
        }
        while (option != 7) {
            System.out.println("Choose Option");
            System.out.println("1: SignUp");
            System.out.println("2: Login");
            System.out.println("3: Fetch Bookings");
            System.out.println("4: Search Trains");
            System.out.println("5: Book a Seat");
            System.out.println("6: Cancel my booking");
            System.out.println("7: Exit the app");
            option = sc.nextInt();
            Train trainSelectedForBooking = new Train();
            switch (option) {
                case 1:
                    System.out.println("Enter Username to Signup");
                    String nameToSignup = sc.next();
                    System.out.println("Enter password to Signup");
                    String passwordToSignup = sc.next();
                    User userToSignup = new User(nameToSignup, passwordToSignup,
                            UserServiceUtil.hashPassword(passwordToSignup), new ArrayList<>(),
                            UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;

                // case 2:
                // System.out.println("Enter Username to Log in");
                // String nameToLogin=sc.next();
                // System.out.println("Enter password to Log in");
                // String passwordToLogin=sc.next();
                // User userToLogin=new User(nameToLogin, passwordToLogin,
                // UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(),
                // UUID.randomUUID().toString());
                // try{
                // userBookingService=new UserBookingService(userToLogin);
                // }
                // catch(IOException ex){
                // return;
                // }
                // break;
                case 2:
                    System.out.println("Enter Username to Log in");
                    String nameToLogin = sc.next();
                    System.out.println("Enter password to Log in");
                    String passwordToLogin = sc.next();

                    User userToLogin = new User(
                            nameToLogin,
                            passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(),
                            UUID.randomUUID().toString());

                    try {
                        userBookingService = new UserBookingService(userToLogin);

                        if (userBookingService.loginUser()) {
                            System.out.println("Login successful");
                        } else {
                            System.out.println("Invalid username or password");
                        }

                    } catch (IOException ex) {
                        System.out.println("Error reading user database");
                    }
                    break;

                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:
                    System.out.println("Enter Source Station");
                    String source = sc.next();
                    System.out.println("Enter Destination Station");
                    String destination = sc.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int i = 1;
                    for (Train t : trains) {
                        System.out.println(i + "Train ID" + t.getTrainId());
                        for (Map.Entry<String, String> e : t.getStationTimes().entrySet()) {
                            System.out.println("Station: " + e.getKey() + " Time: " + e.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3,...");
                    trainSelectedForBooking = trains.get(sc.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out the following seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row : seats) {
                        for (Integer val : row) {
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Please Select a seat by typing row and column");
                    System.out.println("Enter row");
                    int row = sc.nextInt();
                    System.out.println("Enter column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat");
                    Boolean booked = userBookingService.bookTrainSeats(trainSelectedForBooking, row, col);
                    if (booked.equals(Boolean.TRUE)) {
                        System.out.println("Booked! Enjoy your Ride");
                    } else {
                        System.out.println("Can't book this seat");
                    }
                    break;
                case 6:
                    System.out.println("Enter ticketId you want to cancel");
                    String ticketId = sc.next();
                    userBookingService.cancelBooking(ticketId);
                    break;
                default:
                    break;
            }
        }

    }
}
